package com.testproject.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class obj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "OBJ_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "OBJ_ID_SEQ", name = "OBJ_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String name;

	public obj() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public obj(java.lang.Long id, java.lang.String name) {
		this.id = id;
		this.name = name;
	}

}